name: Container
on:
  pull_request:
    # branches:
    #   - master
    # types: [closed]

jobs:
  deploy-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: deploy
        run: |
          git diff origin/${{ github.base_ref }}...origin/${{ github.head_ref }}

